### ISSUE TITLE
Подготовку данных лучше осуществлять до основных действий

### ISSUE THREAD

**Issue by ivanvikvik** [nikishkaa/StudentJavaRevisionTask01Project-master#1]
https://github.com/nikishkaa/StudentJavaRevisionTask01Project-master/blob/8baee8926ce09671d163cb51eb08ac9086da0c05/StudentJavaRevisionTask01Project-master/src/by/itstep/javatraining/revision/task/Task03.java#L31
Активную защиту от дурака лучше разместить раньше основной логики метода.

**Comment by ivanvikvik** [comment]
?

**Comment by nikishkaa** [comment]
Вроде всё исправил
